from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('', views.landing_page, name='landing_page'),
    path('register/', views.register, name='register'),
    path('add_course/', views.CourseCreateView.as_view(),
         name='add_course'),
    path('submit_report/', views.LabReportSubmitView.as_view(),
         name='submit_report'),
    path('grade_report/<int:pk>/',
         views.GradeReportView.as_view(), name='grade_report'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/student/', views.dashboard, name='student_dashboard'),
    path('dashboard/lecturer/', views.dashboard,
         name='lecturer_dashboard'),
    path('dashboard/labtech/', views.dashboard, name='labtech_dashboard'),
    path('add_course/', views.CourseCreateView.as_view(), name='add_course'),
    path('delete_course/<int:course_id>/',
         views.delete_course, name='delete_course'),
    path('enroll_course/', views.enroll_course, name='enroll_course'),
    path('unenroll_course/', views.unenroll_course, name='unenroll_course'),
    path('lab_reports/upload/<int:course_id>/',
         views.upload_lab_report, name='upload_lab_report'),
    path('add_laboratory/', views.add_laboratory, name='add_laboratory'),
    path('lab_content/', views.my_creations, name='view_lab_content'),
    path('course/<int:course_id>/', views.course_detail, name='course_detail'),
    path('ajax/get_laboratories/',
         views.get_laboratories_for_course, name='get_laboratories'),
    path('laboratory/delete/<int:lab_id>/',
         views.delete_laboratory, name='delete_laboratory'),
    path('upload_lab_report/<int:course_id>/',
         views.upload_lab_report, name='upload_lab_report'),
    path('student/dashboard/', views.student_dashboard, name='student_dashboard'),
    path('lab-reports/<int:lab_report_id>/',
         views.lab_report_detail, name='lab_report_detail'),
    #     path('upload_template/', views.upload_lab_template,
    #          name='upload_lab_template'),
    path('list_templates/', views.list_lab_templates, name='list_lab_templates'),
    path('lab/<int:lab_id>/upload_template/',
         views.lab_template_upload, name='lab_template_upload'),

]
