# Generated by Django 5.0.3 on 2024-03-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_laboratory_labtemplate_user_labreport_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labreport',
            old_name='submission_file',
            new_name='submittion_file',
        ),
    ]
