# Generated by Django 5.0.3 on 2024-03-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_submission_file_labreport_submittion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
