# Generated by Django 5.0.3 on 2024-03-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_course_code_alter_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='enrolled_students',
            new_name='student',
        ),
    ]
