# Generated by Django 5.0.3 on 2024-03-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_submittion_file_labreport_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='users.course'),
        ),
    ]
