# Generated by Django 5.0.3 on 2024-03-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_labreport_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='description',
        ),
    ]
