# Generated by Django 5.0.3 on 2024-03-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_title_laboratory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='users.laboratory'),
        ),
    ]
