# Generated by Django 5.0.3 on 2024-03-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_labreport_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='student',
        ),
    ]
