# Generated by Django 5.0.3 on 2024-03-25 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_labreport_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labreport',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
