# Generated by Django 5.0.3 on 2024-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_laboratory_creator_labreport_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
