# Generated by Django 5.0.3 on 2024-03-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_labreport_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='lab_report',
        ),
        migrations.AddField(
            model_name='grade',
            name='lab_template',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='users.labtemplate'),
            preserve_default=False,
        ),
    ]
