# Generated by Django 5.0.3 on 2024-03-27 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_grade_lab_report_grade_lab_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratories', to=settings.AUTH_USER_MODEL),
        ),
    ]
