# Generated by Django 5.0.3 on 2024-03-27 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_laboratory_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='lab_template',
        ),
        migrations.AddField(
            model_name='grade',
            name='lab_report',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='users.labreport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='users.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labreport',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='users.course'),
        ),
    ]
