# Generated by Django 5.0.3 on 2024-03-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_grade_lab_template_grade_lab_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='report_type',
            field=models.CharField(choices=[('IND', 'Individual'), ('GRP', 'Group')], default='IND', max_length=3),
        ),
    ]
