# Generated by Django 5.0.3 on 2024-03-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_labreport_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtemplate',
            name='laboratory',
        ),
        migrations.AddField(
            model_name='labtemplate',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_templates', to='users.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtemplate',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
