# Generated by Django 5.0.3 on 2024-03-31 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_labtemplate_laboratory_labtemplate_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to='users.labtemplate'),
        ),
    ]
