# Generated by Django 5.0.3 on 2024-03-31 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_labreport_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtemplate',
            name='laboratory',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.laboratory'),
            preserve_default=False,
        ),
    ]
