# Generated by Django 5.0.3 on 2024-03-31 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_labtemplate_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtemplate',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.laboratory'),
        ),
    ]
