# Generated by Django 5.0.3 on 2024-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_labtemplate_template_file_templatesection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesection',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatesection',
            name='visible_to_students',
            field=models.BooleanField(default=True),
        ),
    ]
