# Generated by Django 5.0.3 on 2024-04-10 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_sectiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesection',
            name='section_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.sectiontype'),
            preserve_default=False,
        ),
    ]
