# Generated by Django 5.0.3 on 2024-04-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_templatesection_section_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesection',
            name='order',
        ),
    ]
