# Generated by Django 5.0.3 on 2024-04-14 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_templatesection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lab_reports', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
