# Generated by Django 5.0.3 on 2024-04-15 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_labreport_student_alter_labreport_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_lab_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
