# Generated by Django 5.0.3 on 2024-04-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_labreport_creator_alter_labreport_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='student',
        ),
    ]
