# Generated by Django 5.0.3 on 2024-04-15 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_labreport_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sectiontype'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
