# Generated by Django 5.0.3 on 2024-04-15 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_studentresponse_graded_alter_studentresponse_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresponse',
            name='graded',
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.templatesection'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
