# Generated by Django 5.0.3 on 2024-04-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_studentresponse_graded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='lab_report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.labreport'),
            preserve_default=False,
        ),
    ]
