# Generated by Django 5.0.4 on 2024-05-21 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_studentresponse_lab_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesection',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LabReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='lab_submissions/')),
                ('lab_report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.labreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
