# Generated by Django 5.0.4 on 2024-05-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_templatesection_marks_labreportsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='users.labtemplate'),
        ),
    ]
