# Generated by Django 5.0.4 on 2024-05-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_enrollment_course_alter_enrollment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtemplate',
            name='enrolled_students',
        ),
        migrations.AlterField(
            model_name='labreport',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to='users.labtemplate'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
