# Generated by Django 5.0.4 on 2024-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_studentresponse_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresponse',
            name='marks',
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='awarded_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
