# Generated by Django 5.0.4 on 2024-05-23 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_remove_studentresponse_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresponse',
            name='awarded_marks',
        ),
        migrations.AddField(
            model_name='labreport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_lab_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lab_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
