# Generated by Django 5.0.4 on 2024-06-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_labreport_is_active_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='lecturer_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
