# Generated by Django 5.0.4 on 2024-06-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_studentresponse_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='student_feedback',
            field=models.TextField(blank=True),
        ),
    ]
