# Generated by Django 5.0.4 on 2024-06-27 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_rename_feedback_studentresponse_tech_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
